import {
  Activity01Icon,
  AnalyticsUpIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowUp01Icon,
  Building03Icon,
  Calendar03Icon,
  Camera01Icon,
  Cancel01Icon,
  ClipboardIcon,
  Clock01Icon,
  DashboardSquare01Icon,
  FavouriteIcon,
  GridIcon,
  HeadphonesIcon,
  HelpCircleIcon,
  Home01Icon,
  Location01Icon,
  Logout01Icon,
  Megaphone01Icon,
  Message01Icon,
  Restaurant01Icon,
  Search01Icon,
  SecurityCheckIcon,
  Settings01Icon,
  ShoppingBag01Icon,
  ShoppingBasketAdd03Icon,
  SparklesIcon,
  StarIcon,
  TickDouble02Icon,
  UserIcon,
  UserGroupIcon,
  Wallet01Icon,
} from "@hugeicons/core-free-icons";

export const iconMap = {
  home: Home01Icon,
  places: Location01Icon,
  location: Location01Icon,
  activity: Activity01Icon,
  wallet: Wallet01Icon,
  moments: Camera01Icon,
  camera: Camera01Icon,
  settings: Settings01Icon,
  profile: UserIcon,
  user: UserIcon,
  search: Search01Icon,
  cart: ShoppingBag01Icon,
  shopping: ShoppingBag01Icon,
  addToCart: ShoppingBasketAdd03Icon,
  star: StarIcon,
  tickDouble: TickDouble02Icon,
  restaurant: Restaurant01Icon,
  grid: GridIcon,
  shield: SecurityCheckIcon,
  heart: FavouriteIcon,
  sparkles: SparklesIcon,
  calendar: Calendar03Icon,
  users: UserGroupIcon,
  help: HelpCircleIcon,
  message: Message01Icon,
  clock: Clock01Icon,
  trendingUp: ArrowUp01Icon,
  trendingDown: ArrowDown01Icon,
  building: Building03Icon,
  logout: Logout01Icon,
  close: Cancel01Icon,
  dashboard: DashboardSquare01Icon,
  clipboard: ClipboardIcon,
  finance: Wallet01Icon,
  insights: AnalyticsUpIcon,
  marketing: Megaphone01Icon,
  headphones: HeadphonesIcon,
  chevronLeft: ArrowLeft01Icon,
} as const;

export type IconName = keyof typeof iconMap;
