import { IMG } from "./images";
import type { WeeklyHours } from "@/lib/place-hours";

export type PlaceType =
  | "restaurant"
  | "cafe"
  | "bar"
  | "lounge"
  | "bistro"
  | "fine-dining"
  | "bakery";

export type PlaceFilter = "all" | PlaceType;

export type PlaceAddress = {
  street: string;
  locality: string;
  region: string;
  country: string;
};

export type PlaceGeo = {
  lat: number;
  lng: number;
};

export type PlaceReview = {
  author: string;
  rating: number;
  text: string;
  date?: string;
};

export type PlaceMenuItem = {
  name: string;
  description?: string;
  price?: string;
};

export type PlaceMenuSection = {
  name: string;
  items: readonly PlaceMenuItem[];
};

export type PlaceFAQ = {
  question: string;
  answer: string;
};

export type PlaceBase = {
  id: string;
  name: string;
  category: string;
  type: PlaceType;
  location: string;
  rating: number;
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  description: string;
  image: (typeof IMG)[keyof typeof IMG];
  website?: string;
  tags: readonly string[];
  hours: WeeklyHours;
  featured?: boolean;
};

export type PlaceSeed = PlaceBase & {
  slug?: string;
  address?: Partial<PlaceAddress>;
  geo?: Partial<PlaceGeo>;
  phone?: string;
  reviews?: readonly PlaceReview[];
  menu?: readonly PlaceMenuSection[];
  faqs?: readonly PlaceFAQ[];
  gallery?: readonly string[];
  sameAs?: readonly string[];
  updatedAt?: string;
};

export type Place = PlaceBase & {
  slug: string;
  address: PlaceAddress;
  geo: PlaceGeo;
  phone?: string;
  reviews: readonly PlaceReview[];
  menu: readonly PlaceMenuSection[];
  faqs: readonly PlaceFAQ[];
  gallery: readonly string[];
  sameAs: readonly string[];
  updatedAt: string;
};

const daily = (hours: string): WeeklyHours => ({
  monday: hours,
  tuesday: hours,
  wednesday: hours,
  thursday: hours,
  friday: hours,
  saturday: hours,
  sunday: hours,
});

export const places: readonly PlaceSeed[] = [
  {
    id: "boho",
    name: "Boho",
    category: "Restaurant · Afro-fusion",
    type: "restaurant",
    location: "Kiyovu",
    rating: 4.9,
    priceRange: "$$",
    description:
      "Rooftop Afro-fusion dining, craft cocktails, and one of Kigali's best night views.",
    image: IMG.nightView,
    website: "https://www.boho.rw/",
    tags: ["rooftop", "cocktails", "afro-fusion", "nightlife"],
    featured: true,
    hours: {
      monday: "8 AM – 1 AM",
      tuesday: "8 AM – 1 AM",
      wednesday: "8 AM – 1 AM",
      thursday: "8 AM – 1 AM",
      friday: "8 AM – 2 AM",
      saturday: "8 AM – 2 AM",
      sunday: "8 AM – 2 AM",
    },
  },
  {
    id: "pili-pili",
    name: "Pili Pili",
    category: "Restaurant & Lounge",
    type: "lounge",
    location: "Kibagabaga",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Wood-fired pizza, sunset sessions, and poolside dining on the hills of Kigali.",
    image: IMG.outdoorDining,
    website: "https://www.pilipilirwanda.rw/",
    tags: ["pizza", "pool", "sunset", "lounge"],
    featured: true,
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "heaven",
    name: "Heaven Restaurant",
    category: "Restaurant · Modern African",
    type: "restaurant",
    location: "Kiyovu",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Panoramic city views with thoughtfully prepared local and international cuisine.",
    image: IMG.elegantTable,
    website: "https://heavenrwanda.com/",
    tags: ["views", "african", "hotel", "brunch"],
    featured: true,
    hours: daily("6:30 AM – 10 PM"),
  },
  {
    id: "casa-verde",
    name: "Casa Verde",
    category: "Café · Resto · Bar",
    type: "cafe",
    location: "Kiyovu",
    rating: 4.7,
    priceRange: "$$",
    description:
      "All-day café, restaurant, and bar with a relaxed garden setting in the city center.",
    image: IMG.modernCafe,
    website: "https://casaverde.rw/",
    tags: ["garden", "coffee", "bar", "all-day"],
    featured: true,
    hours: daily("7 AM – 11 PM"),
  },
  {
    id: "question-coffee",
    name: "Question Coffee",
    category: "Café · Specialty coffee",
    type: "cafe",
    location: "Gishushu",
    rating: 4.9,
    priceRange: "$$",
    description:
      "Farm-to-cup Rwandan specialty coffee from women-led cooperatives, plus barista training.",
    image: IMG.modernElegance,
    website: "https://www.questioncoffee.com/",
    sameAs: ["https://www.instagram.com/questioncaferw/"],
    tags: ["specialty coffee", "training", "women-led", "farm to cup"],
    featured: true,
    hours: {
      monday: "8 AM – 6 PM",
      tuesday: "8 AM – 6 PM",
      wednesday: "8 AM – 6 PM",
      thursday: "8 AM – 6 PM",
      friday: "8 AM – 6 PM",
      saturday: "9 AM – 5 PM",
      sunday: "9 AM – 5 PM",
    },
  },
  {
    id: "choose-kigali",
    name: "Choose Kigali",
    category: "Fine dining · Art gallery",
    type: "fine-dining",
    location: "Kiyovu",
    rating: 4.9,
    priceRange: "$$$$",
    description:
      "Rwanda's premiere art gallery paired with omakase tasting menus and guest chef residencies.",
    image: IMG.portrait,
    website: "https://www.choosekigali.com/",
    tags: ["art", "tasting menu", "wine", "omakase"],
    featured: true,
    hours: {
      monday: "Closed",
      tuesday: "6 PM – 11 PM",
      wednesday: "6 PM – 11 PM",
      thursday: "6 PM – 11 PM",
      friday: "6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "peacock-cafe",
    name: "Peacock Cafe & Gardens",
    category: "Café · Garden restaurant",
    type: "cafe",
    location: "Kiyovu",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Coffee shop and garden restaurant in Kiyovu — calm greenery and refined plates.",
    image: IMG.aerial,
    website: "https://peacockgarden.net/",
    tags: ["garden", "coffee", "lunch", "healthy"],
    featured: true,
    hours: daily("8 AM – 10 PM"),
  },
  {
    id: "inzora",
    name: "Inzora Rooftop Café",
    category: "Café · Rooftop",
    type: "cafe",
    location: "Nyarutarama",
    rating: 4.8,
    priceRange: "$$",
    description:
      "Quiet rooftop café above Ikirezi Bookstore — coffee, light bites, and leafy views.",
    image: IMG.rooftop,
    website: "https://inzorarooftopcafe.com/",
    sameAs: [
      "https://www.instagram.com/inzorarooftopcafe/",
      "https://www.facebook.com/inzorarooftopcafe/",
    ],
    tags: ["rooftop", "bookstore", "quiet", "vegetarian"],
    featured: true,
    hours: {
      monday: "8 AM – 6 PM",
      tuesday: "8 AM – 6 PM",
      wednesday: "8 AM – 6 PM",
      thursday: "8 AM – 6 PM",
      friday: "8 AM – 6 PM",
      saturday: "9 AM – 5 PM",
      sunday: "Closed",
    },
  },
  {
    id: "nyurah",
    name: "Nyurah",
    category: "Fine dining · Contemporary African",
    type: "fine-dining",
    location: "City Centre",
    rating: 4.9,
    priceRange: "$$$$",
    description:
      "Seasonal contemporary African cuisine in Alliance Towers — reservations recommended.",
    image: IMG.sophisticated,
    website: "https://www.nyurah.com/",
    tags: ["fine dining", "seasonal", "african", "vegan options"],
    hours: {
      monday: "Closed",
      tuesday: "12 PM – 3 PM, 6 PM – 11 PM",
      wednesday: "12 PM – 3 PM, 6 PM – 11 PM",
      thursday: "12 PM – 3 PM, 6 PM – 11 PM",
      friday: "12 PM – 3 PM, 6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "lilly",
    name: "Lilly Fine Dining",
    category: "Fine dining",
    type: "fine-dining",
    location: "Kimihurura",
    rating: 4.9,
    priceRange: "$$$$",
    description:
      "Contemporary fine dining with seasonal menus and an intimate Kimihurura setting.",
    image: IMG.elegantTable,
    website: "https://lilly-rwanda.com/",
    tags: ["seasonal", "date night", "wine"],
    hours: {
      monday: "Closed",
      tuesday: "6 PM – 11 PM",
      wednesday: "6 PM – 11 PM",
      thursday: "6 PM – 11 PM",
      friday: "6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "le-youkounkoun",
    name: "Le Youkounkoun",
    category: "Fine dining · African fusion",
    type: "fine-dining",
    location: "City Centre",
    rating: 4.8,
    priceRange: "$$$$",
    description:
      "Elevated African fusion at Simba Center — tasting menus and a polished dining room.",
    image: IMG.joyfulScene,
    website: "https://www.leyoukounkoun.rw/",
    tags: ["african fusion", "tasting menu", "simba center"],
    hours: {
      monday: "Closed",
      tuesday: "12 PM – 3 PM, 6 PM – 11 PM",
      wednesday: "12 PM – 3 PM, 6 PM – 11 PM",
      thursday: "12 PM – 3 PM, 6 PM – 11 PM",
      friday: "12 PM – 3 PM, 6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "yt-burger",
    name: "Y&T Burger & Wine Bistro",
    category: "Restaurant · Burgers & wine",
    type: "restaurant",
    location: "Gishushu",
    rating: 4.7,
    priceRange: "$$",
    description:
      "Gourmet burgers, natural wines, and a lively bistro vibe in Gishushu.",
    image: IMG.gourmetBurger,
    website: "https://www.ytburger.com/",
    tags: ["burgers", "wine", "bistro"],
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "fayrouz",
    name: "Fayrouz",
    category: "Restaurant · Lebanese",
    type: "restaurant",
    location: "Kigali",
    rating: 4.7,
    priceRange: "$$",
    description:
      "Lebanese mezze, grills, and Middle Eastern flavors in a warm, social setting.",
    image: IMG.cozy,
    website: "https://fayrouz-africa.com/",
    tags: ["lebanese", "mezze", "middle eastern"],
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "repub-lounge",
    name: "Repub Lounge",
    category: "Restaurant · East African",
    type: "lounge",
    location: "Kimihurura",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Upscale East African cuisine across two floors — a Kimihurura institution since 2006.",
    image: IMG.tropical,
    website: "https://republounge.com/",
    tags: ["east african", "institution", "two floors"],
    hours: daily("12 PM – 10 PM"),
  },
  {
    id: "poivre-noir",
    name: "Poivre Noir",
    category: "Bistro · International",
    type: "bistro",
    location: "Kimihurura",
    rating: 4.7,
    priceRange: "$$$",
    description:
      "Contemporary bistro plates, wine pairings, and private dining in Kimihurura.",
    image: IMG.serene,
    website: "https://poivrenoirbistro.com/",
    tags: ["bistro", "wine", "private dining"],
    hours: {
      monday: "Closed",
      tuesday: "12 PM – 10 PM",
      wednesday: "12 PM – 10 PM",
      thursday: "12 PM – 10 PM",
      friday: "12 PM – 10 PM",
      saturday: "12 PM – 10 PM",
      sunday: "12 PM – 10 PM",
    },
  },
  {
    id: "meze-fresh",
    name: "Meze Fresh",
    category: "Restaurant · Mexican",
    type: "restaurant",
    location: "Kacyiru",
    rating: 4.6,
    priceRange: "$",
    description:
      "Kigali's original build-your-own burrito bar — tacos, bowls, and fast-casual Mexican.",
    image: IMG.burgers,
    tags: ["mexican", "burritos", "fast casual", "budget"],
    hours: {
      monday: "Closed",
      tuesday: "11 AM – 11 PM",
      wednesday: "11 AM – 11 PM",
      thursday: "11 AM – 11 PM",
      friday: "11 AM – 11 PM",
      saturday: "11 AM – 11 PM",
      sunday: "12 PM – 8 PM",
    },
  },
  {
    id: "brioche",
    name: "Brioche",
    category: "Bakery · Café bistro",
    type: "bakery",
    location: "Kacyiru",
    rating: 4.7,
    priceRange: "$$",
    description:
      "French-inspired pastries, breads, and espresso — multiple locations across Kigali.",
    image: IMG.creamyDrink,
    website: "https://www.briocherwanda.com/",
    sameAs: ["https://www.instagram.com/briocherwanda/"],
    tags: ["bakery", "pastries", "coffee", "breakfast", "brunch"],
    hours: daily("7 AM – 9 PM"),
  },
  {
    id: "kivu-noir",
    name: "Kivu Noir",
    category: "Café · Specialty coffee",
    type: "cafe",
    location: "Kiyovu",
    rating: 4.8,
    priceRange: "$$",
    description:
      "Specialty coffee bar with modern interiors and all-day brews in central Kigali.",
    image: IMG.modernCafe,
    website: "https://kivunoir.com/",
    sameAs: ["https://www.instagram.com/kivunoircafe/"],
    tags: ["specialty coffee", "work-friendly", "espresso"],
    hours: daily("7 AM – 8 PM"),
  },
  {
    id: "rubia",
    name: "Rubia Coffee Roasters",
    category: "Café · Coffee roastery",
    type: "cafe",
    location: "Kimihurura",
    rating: 4.8,
    priceRange: "$$",
    description:
      "Craft coffee roasting and café service with curated beans and minimalist design.",
    image: IMG.creamyDrink,
    sameAs: ["https://www.instagram.com/rubiacoffeeroasters/"],
    tags: ["roastery", "coffee", "brunch"],
    hours: daily("7 AM – 7 PM"),
  },
  {
    id: "indabo",
    name: "Indabo Cafe",
    category: "Café · Garden",
    type: "cafe",
    location: "Kiyovu",
    rating: 4.7,
    priceRange: "$$",
    description:
      "Lush garden café popular for relaxed brunches, coffee, and leafy outdoor seating.",
    image: IMG.tropical,
    sameAs: ["https://www.instagram.com/indabocafe/"],
    tags: ["garden", "brunch", "green space"],
    hours: daily("8 AM – 8 PM"),
  },
  {
    id: "riders-lounge",
    name: "Riders Lounge",
    category: "Lounge · Cocktails",
    type: "lounge",
    location: "Kacyiru",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Popular nightlife lounge at Kigali Heights with DJ nights, cocktails, and events.",
    image: IMG.nightView,
    website: "https://ridersloungeafrica.com/",
    sameAs: ["https://www.instagram.com/ridersloungerw/"],
    tags: ["nightlife", "dj", "cocktails", "events"],
    hours: daily("4 PM – 2 AM"),
  },
  {
    id: "la-creola",
    name: "La Creola",
    category: "Restaurant · African & seafood",
    type: "restaurant",
    location: "Kigali",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Contemporary African dining with seafood-forward plates and an elevated dinner atmosphere.",
    image: IMG.elegantTable,
    tags: ["african cuisine", "seafood", "dinner"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "the-hut",
    name: "The HUT Restaurant & Boutique Hotel",
    category: "Restaurant · Fusion",
    type: "restaurant",
    location: "Kigali",
    rating: 4.7,
    priceRange: "$$$",
    description:
      "Fusion and grill favorites in a lively setting with a boutique-hotel vibe.",
    image: IMG.outdoorDining,
    tags: ["fusion", "grill", "boutique"],
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "filini",
    name: "Filini Restaurant & Bar",
    category: "Restaurant · Italian",
    type: "restaurant",
    location: "Kigali",
    rating: 4.8,
    priceRange: "$$$",
    description:
      "Upscale Italian dining known for pasta, pizza, and polished service.",
    image: IMG.pizzaInterior,
    tags: ["italian", "pasta", "pizza", "date night"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "fusion-kigali",
    name: "Fusion Restaurant",
    category: "Fine dining · International fusion",
    type: "fine-dining",
    location: "Kigali",
    rating: 4.8,
    priceRange: "$$$$",
    description:
      "Fine dining fusion concept with tasting-style plates and refined ambiance.",
    image: IMG.modernElegance,
    tags: ["fine dining", "fusion", "chef menu"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "cucina",
    name: "Cucina Restaurant",
    category: "Restaurant · Italian & European",
    type: "restaurant",
    location: "Kigali",
    rating: 4.7,
    priceRange: "$$$",
    description:
      "Elegant European-Italian menu with wood-fired classics and premium wine pairings.",
    image: IMG.serene,
    tags: ["italian", "european", "wine"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "khana-khazana",
    name: "Khana Khazana",
    category: "Restaurant · Indian",
    type: "restaurant",
    location: "Kigali",
    rating: 4.7,
    priceRange: "$$$",
    description:
      "Long-running Indian restaurant with rich curries, tandoori dishes, and vegetarian options.",
    image: IMG.cozy,
    tags: ["indian", "tandoori", "vegetarian-friendly"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "14th-avenue",
    name: "14th Avenue Wine Bar & Restaurant",
    category: "Bistro · Wine bar",
    type: "bistro",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Wine-focused bistro with international small plates and a relaxed upscale crowd.",
    image: IMG.beachDrink,
    tags: ["wine bar", "small plates", "bistro"],
    hours: daily("12 PM – 12 AM"),
  },
  {
    id: "inka-steakhouse",
    name: "Inka Steakhouse",
    category: "Restaurant · Steakhouse",
    type: "restaurant",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$$$",
    description:
      "Classic steakhouse menu with grilled meats, premium cuts, and business-dinner ambiance.",
    image: IMG.joyfulScene,
    tags: ["steakhouse", "grill", "premium cuts"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "bourbon-coffee",
    name: "Bourbon Coffee",
    category: "Café · Coffee chain",
    type: "cafe",
    location: "City Centre",
    rating: 4.5,
    priceRange: "$$",
    description:
      "Rwandan coffee chain offering espresso drinks, pastries, and casual coworking spots.",
    image: IMG.creamyDrink,
    website: "https://bourboncoffeeafrica.com/",
    sameAs: ["https://www.instagram.com/bourboncoffee_rw/"],
    tags: ["coffee", "pastries", "coworking", "all-day"],
    hours: daily("7 AM – 9 PM"),
  },
  {
    id: "shokola",
    name: "Shokola Cafe",
    category: "Café · Brunch",
    type: "cafe",
    location: "Kacyiru",
    rating: 4.6,
    priceRange: "$$",
    description:
      "Rooftop café known for healthy brunch options, juices, and relaxed daytime vibes.",
    image: IMG.modernCafe,
    tags: ["brunch", "healthy", "rooftop", "juice"],
    hours: daily("8 AM – 7 PM"),
  },
  {
    id: "java-house",
    name: "Java House Kigali",
    category: "Café · Casual dining",
    type: "cafe",
    location: "Remera",
    rating: 4.5,
    priceRange: "$$",
    description:
      "Popular all-day café and diner with coffee, breakfast plates, and family-friendly seating.",
    image: IMG.outdoorDining,
    tags: ["breakfast", "coffee", "casual dining"],
    hours: daily("7 AM – 10 PM"),
  },
  {
    id: "le-petit-chalet",
    name: "Le Petit Chalet",
    category: "Restaurant · European",
    type: "restaurant",
    location: "Nyarutarama",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Elegant European cuisine with terrace seating and a quiet fine-casual atmosphere.",
    image: IMG.serene,
    tags: ["european", "terrace", "date night"],
    hours: daily("12 PM – 10 PM"),
  },
  {
    id: "brachetto",
    name: "Brachetto Restaurant & Tapas",
    category: "Bistro · Tapas bar",
    type: "bistro",
    location: "Kimihurura",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Tapas-style menu with cocktails and a social evening atmosphere in Kimihurura.",
    image: IMG.beachDrink,
    tags: ["tapas", "cocktails", "bistro"],
    hours: daily("4 PM – 12 AM"),
  },
  {
    id: "the-rock",
    name: "The Rock Cocktail Bar & Bistro",
    category: "Bar · Cocktail bistro",
    type: "bar",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Night-focused cocktail bar and bistro with curated drinks and upbeat weekend energy.",
    image: IMG.nightView,
    tags: ["cocktails", "bistro", "nightlife"],
    hours: daily("5 PM – 2 AM"),
  },
  {
    id: "iriba-bar",
    name: "Iriba Bar & Terrace",
    category: "Bar · Terrace lounge",
    type: "bar",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Open-air terrace bar with city views, grills, and evening music sessions.",
    image: IMG.tropical,
    tags: ["terrace", "views", "bar bites", "music"],
    hours: daily("3 PM – 1 AM"),
  },
  {
    id: "le-epicurien",
    name: "L'epicurien",
    category: "Fine dining · French-inspired",
    type: "fine-dining",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$$$",
    description:
      "French-inspired fine dining with chef-led menus and polished service.",
    image: IMG.elegantTable,
    tags: ["french", "fine dining", "chef menu"],
    hours: {
      monday: "Closed",
      tuesday: "6 PM – 11 PM",
      wednesday: "6 PM – 11 PM",
      thursday: "6 PM – 11 PM",
      friday: "6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "onecup-roasters",
    name: "Onecup Roasters",
    category: "Café · Specialty roastery",
    type: "cafe",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$",
    description:
      "Small-batch coffee roastery and café with pour-over programs and barista-focused service.",
    image: IMG.modernElegance,
    tags: ["roastery", "specialty coffee", "pour-over"],
    hours: daily("7:30 AM – 7 PM"),
  },
  {
    id: "pan-afrikan",
    name: "Kigali Pan-Afrikan Kitchen",
    category: "Restaurant · Pan-African",
    type: "restaurant",
    location: "City Centre",
    rating: 4.6,
    priceRange: "$$",
    description:
      "Pan-African plates celebrating regional flavors in a lively downtown setting.",
    image: IMG.pizzaInterior,
    tags: ["pan-african", "local", "downtown"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "habesha",
    name: "Habesha Ethiopian Restaurant",
    category: "Restaurant · Ethiopian",
    type: "restaurant",
    location: "Kiyovu",
    rating: 4.7,
    priceRange: "$$",
    description:
      "Traditional injera platters, coffee ceremony, and shared Ethiopian dining.",
    image: IMG.cozy,
    tags: ["ethiopian", "injera", "coffee ceremony", "shared plates"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "chomad",
    name: "Choma'd Bar & Grill",
    category: "Bar & grill · Nyama choma",
    type: "bar",
    location: "Gishushu",
    rating: 4.6,
    priceRange: "$$",
    description:
      "Grilled meats, cold drinks, and a casual after-work crowd near Kigali Heights.",
    image: IMG.beachDrink,
    tags: ["grill", "nyama choma", "after work", "casual"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "sole-luna",
    name: "Sole Luna",
    category: "Restaurant · Italian",
    type: "restaurant",
    location: "Kiyovu",
    rating: 4.7,
    priceRange: "$$$",
    description:
      "Wood-fired pizza, handmade pasta, and Italian wines in a cozy Kiyovu trattoria.",
    image: IMG.pizzaInterior,
    tags: ["italian", "pizza", "pasta", "wine"],
    hours: {
      monday: "Closed",
      tuesday: "12 PM – 11 PM",
      wednesday: "12 PM – 11 PM",
      thursday: "12 PM – 11 PM",
      friday: "12 PM – 11 PM",
      saturday: "12 PM – 11 PM",
      sunday: "12 PM – 11 PM",
    },
  },
  {
    id: "chess-cafe",
    name: "Chess Café",
    category: "Café · Games lounge",
    type: "cafe",
    location: "City Centre",
    rating: 4.5,
    priceRange: "$",
    description:
      "Relaxed café with board games, snacks, and coffee in the heart of downtown Kigali.",
    image: IMG.modernCafe,
    tags: ["games", "coffee", "casual", "downtown"],
    hours: daily("9 AM – 9 PM"),
  },
  {
    id: "marcos-italian",
    name: "Marco's Italian Restaurant & Lounge",
    category: "Restaurant · Italian",
    type: "restaurant",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Italian comfort classics, pizza, and lounge-style evenings in a stylish dining room.",
    image: IMG.pizzaInterior,
    tags: ["italian", "pizza", "pasta", "lounge"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "mini-tamu-tamu",
    name: "Mini Tamu Tamu",
    category: "Restaurant · East African",
    type: "restaurant",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$",
    description:
      "Casual East African kitchen serving local favorites and generous daily plates.",
    image: IMG.joyfulScene,
    tags: ["east african", "local dishes", "casual"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "chez-yasmine",
    name: "Chez Yasmine",
    category: "Bistro · Mediterranean",
    type: "bistro",
    location: "Kimihurura",
    rating: 4.6,
    priceRange: "$$$",
    description:
      "Mediterranean-inspired bistro with grilled specialties and warm evening ambiance.",
    image: IMG.cozy,
    tags: ["mediterranean", "grill", "bistro"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "essence-bar-grill",
    name: "Essence Bar & Grill",
    category: "Bar & grill",
    type: "bar",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Contemporary grill and drinks menu in an upscale lounge atmosphere.",
    image: IMG.beachDrink,
    tags: ["bar", "grill", "cocktails"],
    hours: daily("3 PM – 1 AM"),
  },
  {
    id: "billys-bistro",
    name: "Billy's Bistro Bar",
    category: "Bistro · Bar",
    type: "bistro",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Neighborhood bistro bar with craft drinks, comfort plates, and lively evenings.",
    image: IMG.nightView,
    tags: ["bistro", "bar", "casual nights"],
    hours: daily("4 PM – 1 AM"),
  },
  {
    id: "tung-chinese",
    name: "Tung Chinese Cuisine",
    category: "Restaurant · Chinese",
    type: "restaurant",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$",
    description:
      "Classic Chinese menu with family-style dishes and downtown convenience.",
    image: IMG.serene,
    tags: ["chinese", "family-style", "takeout"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "sundowner",
    name: "Sundowner Kigali",
    category: "Lounge · Sunset bar",
    type: "lounge",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Sunset-focused rooftop lounge with cocktails, sharing plates, and city views.",
    image: IMG.rooftop,
    tags: ["sunset", "rooftop", "cocktails"],
    hours: daily("4 PM – 1 AM"),
  },
  {
    id: "casa-keza",
    name: "Casa Keza",
    category: "Café · Garden",
    type: "cafe",
    location: "Kigali",
    rating: 4.6,
    priceRange: "$$",
    description:
      "Garden café and creative space with artisanal drinks and a calm daytime crowd.",
    image: IMG.tropical,
    tags: ["garden", "coffee", "creative space"],
    hours: daily("8 AM – 8 PM"),
  },
  {
    id: "tea-house-boutique",
    name: "Tea House Boutique",
    category: "Café · Tea room",
    type: "cafe",
    location: "Kigali",
    rating: 4.4,
    priceRange: "$$",
    description:
      "Tea-first boutique café with pastries, light lunches, and cozy interiors.",
    image: IMG.creamyDrink,
    tags: ["tea", "pastries", "cozy"],
    hours: daily("8 AM – 7 PM"),
  },
  {
    id: "umut-cafe",
    name: "Umut Cafe",
    category: "Café · Casual",
    type: "cafe",
    location: "Kigali",
    rating: 4.4,
    priceRange: "$",
    description:
      "Casual city café for quick coffee, snacks, and affordable meals.",
    image: IMG.modernCafe,
    tags: ["casual", "budget", "coffee"],
    hours: daily("7 AM – 8 PM"),
  },
  {
    id: "zen-oriental",
    name: "Zen Oriental Cuisine",
    category: "Restaurant · Asian",
    type: "restaurant",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$",
    description:
      "Pan-Asian restaurant known for sushi, wok dishes, and sleek modern interiors.",
    image: IMG.modernElegance,
    tags: ["asian", "sushi", "wok"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "afrika-bite",
    name: "Afrika Bite",
    category: "Restaurant · African",
    type: "restaurant",
    location: "Kigali",
    rating: 4.4,
    priceRange: "$$",
    description:
      "Affordable African comfort food with grilled options and quick service.",
    image: IMG.joyfulScene,
    tags: ["african", "comfort food", "casual"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "le-chantier",
    name: "Le Chantier",
    category: "Bistro · French-inspired",
    type: "bistro",
    location: "Kiyovu",
    rating: 4.5,
    priceRange: "$$$",
    description: "A relaxed French-style bistro with classic mains and curated wine pairings.",
    image: IMG.serene,
    tags: ["bistro", "french-inspired", "wine"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "papyrus-lounge",
    name: "Papyrus Lounge",
    category: "Lounge · Live music",
    type: "lounge",
    location: "Kimihurura",
    rating: 4.4,
    priceRange: "$$$",
    description: "Evening lounge with live sets, cocktails, and a polished indoor-outdoor setup.",
    image: IMG.nightView,
    tags: ["lounge", "music", "cocktails"],
    hours: daily("5 PM – 2 AM"),
  },
  {
    id: "forest-corner",
    name: "Forest Corner Cafe",
    category: "Café · Nature",
    type: "cafe",
    location: "Nyarutarama",
    rating: 4.4,
    priceRange: "$$",
    description: "Green corner cafe with specialty brews and quiet seating for long catchups.",
    image: IMG.tropical,
    tags: ["cafe", "green", "quiet"],
    hours: daily("8 AM – 8 PM"),
  },
  {
    id: "skyline-bites",
    name: "Skyline Bites",
    category: "Restaurant · Rooftop",
    type: "restaurant",
    location: "City Centre",
    rating: 4.3,
    priceRange: "$$",
    description: "Rooftop restaurant serving grilled favorites with broad city views.",
    image: IMG.rooftop,
    tags: ["rooftop", "grill", "city views"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "golden-spoon",
    name: "Golden Spoon",
    category: "Restaurant · Family dining",
    type: "restaurant",
    location: "Remera",
    rating: 4.3,
    priceRange: "$$",
    description: "Family-friendly all-day restaurant with broad menus and generous portions.",
    image: IMG.cozy,
    tags: ["family", "all-day", "casual"],
    hours: daily("10 AM – 10 PM"),
  },
  {
    id: "mint-leaf",
    name: "Mint Leaf Kigali",
    category: "Restaurant · Indian",
    type: "restaurant",
    location: "Kacyiru",
    rating: 4.5,
    priceRange: "$$$",
    description: "Modern Indian kitchen with flavorful curries, tandoori plates, and mocktails.",
    image: IMG.modernElegance,
    tags: ["indian", "tandoori", "dinner"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "hillside-bakery",
    name: "Hillside Bakery",
    category: "Bakery · Artisan",
    type: "bakery",
    location: "Kiyovu",
    rating: 4.2,
    priceRange: "$$",
    description: "Artisan bakery for sourdough, viennoiserie, and strong morning coffee.",
    image: IMG.creamyDrink,
    tags: ["bakery", "artisan", "breakfast"],
    hours: daily("6:30 AM – 7 PM"),
  },
  {
    id: "green-fork",
    name: "Green Fork",
    category: "Café · Healthy bowls",
    type: "cafe",
    location: "Kimironko",
    rating: 4.3,
    priceRange: "$$",
    description: "Healthy cafe focused on salads, bowls, smoothies, and light brunch menus.",
    image: IMG.modernCafe,
    tags: ["healthy", "bowls", "smoothies"],
    hours: daily("8 AM – 8 PM"),
  },
  {
    id: "mamba-lounge",
    name: "Mamba Lounge",
    category: "Lounge · Nightlife",
    type: "lounge",
    location: "Kigali",
    rating: 4.2,
    priceRange: "$$$",
    description: "High-energy lounge with DJs, bottle service, and late-night weekend crowds.",
    image: IMG.nightView,
    tags: ["nightlife", "djs", "late-night"],
    hours: daily("6 PM – 3 AM"),
  },
  {
    id: "kigali-grill-house",
    name: "Kigali Grill House",
    category: "Restaurant · Grill",
    type: "restaurant",
    location: "Gacuriro",
    rating: 4.4,
    priceRange: "$$",
    description: "Popular grill house with burgers, platters, and smokehouse-style plates.",
    image: IMG.gourmetBurger,
    tags: ["grill", "burgers", "platters"],
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "lavana-kigali",
    name: "Lavana Kigali",
    category: "Bistro · International",
    type: "bistro",
    location: "Nyarutarama",
    rating: 4.4,
    priceRange: "$$$",
    description: "Contemporary bistro menu with rotating specials and an elegant terrace.",
    image: IMG.serene,
    tags: ["international", "terrace", "bistro"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "amata-nubuki",
    name: "Amata N'ubuki Boutique Cafe",
    category: "Café · Boutique",
    type: "cafe",
    location: "Kigali",
    rating: 4.3,
    priceRange: "$$",
    description: "Boutique cafe serving tea, desserts, and curated local snacks.",
    image: IMG.creamyDrink,
    tags: ["boutique", "desserts", "tea"],
    hours: daily("9 AM – 8 PM"),
  },
  {
    id: "bell-tower",
    name: "Bell Tower Chinese",
    category: "Restaurant · Chinese",
    type: "restaurant",
    location: "Kigali",
    rating: 4.3,
    priceRange: "$$",
    description: "Chinese restaurant known for stir-fries, dumplings, and group dining.",
    image: IMG.serene,
    tags: ["chinese", "dumplings", "group dining"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "asian-kitchen",
    name: "Asian Kitchen Kigali",
    category: "Restaurant · Asian fusion",
    type: "restaurant",
    location: "Kimihurura",
    rating: 4.4,
    priceRange: "$$$",
    description: "Asian fusion kitchen blending noodles, curries, and wok-fired mains.",
    image: IMG.modernElegance,
    tags: ["asian fusion", "noodles", "wok"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "turambe-shoppe",
    name: "Turambe Shoppe Cafe",
    category: "Café · Local bites",
    type: "cafe",
    location: "Kigali",
    rating: 4.2,
    priceRange: "$",
    description: "Neighborhood cafe with local pastries, coffee, and quick breakfast options.",
    image: IMG.modernCafe,
    tags: ["local", "pastries", "budget"],
    hours: daily("7 AM – 7 PM"),
  },
  {
    id: "afia-organics",
    name: "Afia Organics Kitchen",
    category: "Restaurant · Healthy",
    type: "restaurant",
    location: "Kigali",
    rating: 4.3,
    priceRange: "$$",
    description: "Organic-forward kitchen with fresh salads, wraps, and clean comfort meals.",
    image: IMG.outdoorDining,
    tags: ["organic", "healthy", "salads"],
    hours: daily("10 AM – 9 PM"),
  },
  {
    id: "lemon-bar",
    name: "Lemon Bar Kigali",
    category: "Bar · Cocktails",
    type: "bar",
    location: "Kimihurura",
    rating: 4.5,
    priceRange: "$$$",
    description: "Cocktail-first bar with rooftop sunset sessions and weekend music events.",
    image: IMG.beachDrink,
    tags: ["cocktails", "sunset", "weekend"],
    hours: daily("4 PM – 2 AM"),
  },
  {
    id: "nemba-cafe",
    name: "Nemba Cafe",
    category: "Café · Specialty coffee",
    type: "cafe",
    location: "Kigali",
    rating: 4.4,
    priceRange: "$$",
    description: "Modern specialty coffee cafe favored by remote workers and students.",
    image: IMG.modernElegance,
    tags: ["coffee", "remote work", "specialty"],
    hours: daily("7 AM – 8 PM"),
  },
  {
    id: "kawa-kigali",
    name: "Kawa Kigali",
    category: "Café · Coffee bar",
    type: "cafe",
    location: "Kacyiru",
    rating: 4.3,
    priceRange: "$$",
    description: "Coffee bar with curated brews and compact brunch offerings.",
    image: IMG.creamyDrink,
    tags: ["coffee bar", "brunch", "casual"],
    hours: daily("7:30 AM – 7:30 PM"),
  },
  {
    id: "remera-social",
    name: "Remera Social",
    category: "Bistro · Social dining",
    type: "bistro",
    location: "Remera",
    rating: 4.3,
    priceRange: "$$$",
    description: "Social bistro with shared plates, cocktails, and after-work energy.",
    image: IMG.cozy,
    tags: ["shared plates", "cocktails", "after-work"],
    hours: daily("12 PM – 12 AM"),
  },
  {
    id: "kigali-garden-grill",
    name: "Kigali Garden Grill",
    category: "Restaurant · Garden grill",
    type: "restaurant",
    location: "Kacyiru",
    rating: 4.2,
    priceRange: "$$",
    description: "Garden-style grill venue with mixed platters and open-air seating.",
    image: IMG.tropical,
    tags: ["garden", "grill", "outdoor"],
    hours: daily("11 AM – 11 PM"),
  },
  {
    id: "nyarutarama-brunch-club",
    name: "Nyarutarama Brunch Club",
    category: "Café · Brunch",
    type: "cafe",
    location: "Nyarutarama",
    rating: 4.2,
    priceRange: "$$",
    description: "Brunch-centric cafe with pancakes, eggs, and signature coffee blends.",
    image: IMG.modernCafe,
    tags: ["brunch", "coffee", "daytime"],
    hours: daily("8 AM – 6 PM"),
  },
  {
    id: "simba-supper",
    name: "Simba Supper Club",
    category: "Fine dining · Chef table",
    type: "fine-dining",
    location: "City Centre",
    rating: 4.6,
    priceRange: "$$$$",
    description: "Chef-driven supper club featuring seasonal tasting menus and pairings.",
    image: IMG.elegantTable,
    tags: ["chef table", "tasting menu", "fine dining"],
    hours: {
      monday: "Closed",
      tuesday: "6 PM – 11 PM",
      wednesday: "6 PM – 11 PM",
      thursday: "6 PM – 11 PM",
      friday: "6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "city-tower-cafe",
    name: "City Tower Cafe",
    category: "Café · Urban",
    type: "cafe",
    location: "City Centre",
    rating: 4.1,
    priceRange: "$",
    description: "Urban cafe for quick coffee runs, light meals, and central convenience.",
    image: IMG.creamyDrink,
    tags: ["urban", "quick bites", "coffee"],
    hours: daily("7 AM – 8 PM"),
  },
  {
    id: "kimihurura-steak-bar",
    name: "Kimihurura Steak Bar",
    category: "Restaurant · Steak & bar",
    type: "restaurant",
    location: "Kimihurura",
    rating: 4.3,
    priceRange: "$$$",
    description: "Steak-and-bar concept with grilled cuts and bold evening cocktails.",
    image: IMG.joyfulScene,
    tags: ["steak", "bar", "dinner"],
    hours: daily("12 PM – 11 PM"),
  },
  {
    id: "kigali-dumpling-house",
    name: "Kigali Dumpling House",
    category: "Restaurant · Asian street food",
    type: "restaurant",
    location: "Kigali",
    rating: 4.2,
    priceRange: "$$",
    description: "Street-food inspired eatery focused on dumplings, noodles, and soups.",
    image: IMG.serene,
    tags: ["dumplings", "noodles", "street food"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "kigali-pasta-room",
    name: "Kigali Pasta Room",
    category: "Restaurant · Italian casual",
    type: "restaurant",
    location: "Kiyovu",
    rating: 4.3,
    priceRange: "$$",
    description: "Casual pasta-forward restaurant with handmade sauces and simple wines.",
    image: IMG.pizzaInterior,
    tags: ["pasta", "italian", "casual"],
    hours: daily("12 PM – 10 PM"),
  },
  {
    id: "sunset-terrace-kigali",
    name: "Sunset Terrace Kigali",
    category: "Lounge · Terrace",
    type: "lounge",
    location: "Nyarutarama",
    rating: 4.3,
    priceRange: "$$$",
    description: "Terrace lounge built around sunset views, light bites, and signature cocktails.",
    image: IMG.rooftop,
    tags: ["sunset", "terrace", "cocktails"],
    hours: daily("4 PM – 1 AM"),
  },
  {
    id: "downtown-noir",
    name: "Downtown Noir Bar",
    category: "Bar · Urban cocktails",
    type: "bar",
    location: "City Centre",
    rating: 4.2,
    priceRange: "$$$",
    description: "Urban cocktail bar with moody interiors and curated late-evening playlists.",
    image: IMG.nightView,
    tags: ["cocktails", "urban", "late night"],
    hours: daily("5 PM – 2 AM"),
  },
  {
    id: "kimironko-kitchen",
    name: "Kimironko Kitchen",
    category: "Restaurant · Local fusion",
    type: "restaurant",
    location: "Kimironko",
    rating: 4.1,
    priceRange: "$$",
    description: "Casual local-fusion kitchen with rotating daily specials and quick service.",
    image: IMG.cozy,
    tags: ["local fusion", "daily specials", "casual"],
    hours: daily("11 AM – 9 PM"),
  },
  {
    id: "rwanda-brew-lab",
    name: "Rwanda Brew Lab",
    category: "Café · Coffee lab",
    type: "cafe",
    location: "Gishushu",
    rating: 4.4,
    priceRange: "$$",
    description: "Coffee lab concept featuring experimental brews and bean tasting flights.",
    image: IMG.modernElegance,
    tags: ["coffee lab", "tasting", "specialty"],
    hours: daily("8 AM – 7 PM"),
  },
  {
    id: "gacuriro-bistro",
    name: "Gacuriro Bistro",
    category: "Bistro · Neighborhood",
    type: "bistro",
    location: "Gacuriro",
    rating: 4.1,
    priceRange: "$$",
    description: "Neighborhood bistro serving comfort dishes, salads, and simple cocktails.",
    image: IMG.outdoorDining,
    tags: ["neighborhood", "comfort food", "bistro"],
    hours: daily("12 PM – 10 PM"),
  },
  {
    id: "virunga-lounge",
    name: "Virunga Lounge",
    category: "Lounge · Premium nightlife",
    type: "lounge",
    location: "Kigali",
    rating: 4.2,
    priceRange: "$$$$",
    description: "Premium nightlife lounge with DJ headliners and a high-energy weekend scene.",
    image: IMG.nightView,
    tags: ["premium", "nightlife", "dj"],
    hours: daily("6 PM – 3 AM"),
  },
  {
    id: "kigali-crepe-corner",
    name: "Kigali Crepe Corner",
    category: "Bakery · Creperie",
    type: "bakery",
    location: "Kacyiru",
    rating: 4.1,
    priceRange: "$",
    description: "Creperie and bakery hybrid with sweet and savory options all day.",
    image: IMG.creamyDrink,
    tags: ["crepes", "bakery", "all-day"],
    hours: daily("8 AM – 8 PM"),
  },
  {
    id: "imigongo-dining",
    name: "Imigongo Dining Room",
    category: "Fine dining · Contemporary African",
    type: "fine-dining",
    location: "Kigali",
    rating: 4.5,
    priceRange: "$$$$",
    description: "Contemporary African dining room centered on seasonal Rwandan produce.",
    image: IMG.elegantTable,
    tags: ["contemporary african", "seasonal", "fine dining"],
    hours: {
      monday: "Closed",
      tuesday: "6 PM – 10:30 PM",
      wednesday: "6 PM – 10:30 PM",
      thursday: "6 PM – 10:30 PM",
      friday: "6 PM – 11 PM",
      saturday: "6 PM – 11 PM",
      sunday: "Closed",
    },
  },
  {
    id: "kibagabaga-cafe-house",
    name: "Kibagabaga Cafe House",
    category: "Café · Community",
    type: "cafe",
    location: "Kibagabaga",
    rating: 4.0,
    priceRange: "$",
    description: "Community-style cafe with affordable coffees, pastries, and light lunches.",
    image: IMG.modernCafe,
    tags: ["community", "budget", "pastries"],
    hours: daily("7 AM – 7 PM"),
  },
  {
    id: "remera-roast",
    name: "Remera Roast",
    category: "Restaurant · Rotisserie",
    type: "restaurant",
    location: "Remera",
    rating: 4.1,
    priceRange: "$$",
    description: "Rotisserie-focused casual spot with chicken platters and house sauces.",
    image: IMG.gourmetBurger,
    tags: ["rotisserie", "platters", "casual"],
    hours: daily("11 AM – 10 PM"),
  },
  {
    id: "kigali-harbor",
    name: "Kigali Harbor Seafood",
    category: "Restaurant · Seafood",
    type: "restaurant",
    location: "City Centre",
    rating: 4.3,
    priceRange: "$$$",
    description: "Seafood-forward restaurant with grilled fish specials and elegant plating.",
    image: IMG.aerial,
    tags: ["seafood", "grill", "dinner"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "kimihurura-cocktail-room",
    name: "Kimihurura Cocktail Room",
    category: "Bar · Mixology",
    type: "bar",
    location: "Kimihurura",
    rating: 4.2,
    priceRange: "$$$",
    description: "Mixology-centered cocktail room with seasonal menus and intimate seating.",
    image: IMG.beachDrink,
    tags: ["mixology", "cocktails", "intimate"],
    hours: daily("5 PM – 1 AM"),
  },
  {
    id: "gisozi-bistro",
    name: "Gisozi Bistro",
    category: "Bistro · Casual",
    type: "bistro",
    location: "Gisozi",
    rating: 4.0,
    priceRange: "$$",
    description: "Friendly bistro serving casual mains, soups, and afternoon coffee.",
    image: IMG.cozy,
    tags: ["casual", "soups", "coffee"],
    hours: daily("10 AM – 9 PM"),
  },
  {
    id: "kigali-spice-route",
    name: "Kigali Spice Route",
    category: "Restaurant · Indian & Middle Eastern",
    type: "restaurant",
    location: "Kigali",
    rating: 4.3,
    priceRange: "$$$",
    description: "Cross-regional spice kitchen serving curry classics and grilled mezze.",
    image: IMG.modernElegance,
    tags: ["indian", "middle eastern", "spiced"],
    hours: daily("12 PM – 10:30 PM"),
  },
  {
    id: "serena-sky-lounge",
    name: "Serena Sky Lounge",
    category: "Lounge · Hotel rooftop",
    type: "lounge",
    location: "City Centre",
    rating: 4.4,
    priceRange: "$$$$",
    description: "Hotel rooftop lounge with skyline views, cocktails, and polished service.",
    image: IMG.rooftop,
    tags: ["hotel", "rooftop", "cocktails"],
    hours: daily("4 PM – 1 AM"),
  },
] as const;

export const placeFilters: { id: PlaceFilter; label: string }[] = [
  { id: "all", label: "All places" },
  { id: "restaurant", label: "Restaurants" },
  { id: "cafe", label: "Cafés" },
  { id: "fine-dining", label: "Fine dining" },
  { id: "bakery", label: "Bakeries" },
  { id: "lounge", label: "Lounges" },
  { id: "bar", label: "Bars & grills" },
  { id: "bistro", label: "Bistros" },
];

export function getFeaturedPlaces(): PlaceSeed[] {
  return places.filter((place) => place.featured);
}

export const placesPage = {
  title: "Explore Kigali",
  headline: "Restaurants, cafés & hidden gems",
  supporting:
    "Browse real spots across Kigali — search by name, neighborhood, or cuisine and see who's open now.",
  searchPlaceholder: "Search by name, area, or cuisine…",
  emptyState: "No places match your search. Try a different keyword or filter.",
} as const;
